version: '3.1'
services: 
  my-sample-app:
    #build: . #this will build the app from local Dockerfile
    image: skr4docker/sample-mongo-nodejs-app:1.0
    ports:
      - 3000:3000
    environment:
      MONGO_DB_USERNAME: ${MONGO_DB_USERANAME}
      MONGO_DB_PWD: ${MONGO_DB_PASS}
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERANAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASS}
  
  mymongoexpress:
    image: mongo-express
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USERANAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASS}
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on: 
      - "mongodb"

